In [42]:
#import libraries
import pandas as pd

In [43]:
df= pd.read_csv("C:\\Users\\Admin\\Downloads\\archive\\Combined_dataset.csv")

In [44]:
# first 5 rows
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [45]:
# last 5 rows
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [46]:
#shape
print(df.shape)

(1000, 24)

In [47]:
print(df.columns)

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [48]:
print(df.dtypes)

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [49]:
df.describe()

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [50]:
 df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [72]:
 df.dropna(axis=1, thresh=500)  # drop any column that does not have at least 500 non-null values.

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,breadcrumbs,product_specifications,amount_of_stars,seller_name,sizes,seller_information,best_offer,more_offers,category,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",Unknown,"[{""size"":""Onesize""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,59925.0
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",Unknown,"[{""size"":""Onesize""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,194233.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",Unknown,"[{""size"":""S""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,677774.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Compartment Closure"",""...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",Unknown,"[{""size"":""Onesize""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1762100.0
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""name"":""Men"",""url"":""https://www.myntra.com/m...","[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,34788.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,11890.0,INR,http://assets.myntassets.com/assets/images/136...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",Unknown,"[{""size"":""Onesize""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,130790.0
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,8900.0,INR,http://assets.myntassets.com/assets/images/168...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,"[{""size"":""Onesize""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,195800.0
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,7950.0,INR,http://assets.myntassets.com/assets/images/170...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Dial Material"",""specif...","{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",Unknown,"[{""size"":""Onesize""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,39750.0
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,2636.0,INR,http://assets.myntassets.com/assets/images/192...,...,"[{""name"":""Accessories"",""url"":""https://www.mynt...","[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",Tru███m R███il,"[{""size"":""Onesize""}]",Sho███o. ███-10█████████enu███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,44812.0
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,699.0,INR,http://assets.myntassets.com/assets/images/186...,...,"[{""name"":""Unisex"",""url"":""https://www.myntra.co...","[{""specification_name"":""Mat Thickness"",""specif...","{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",Unknown,"[{""size"":""Medium""}]",Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,112539.0

In [52]:
df['final_price'] = df['final_price'].astype(str).str.replace(r'[₹,\"\s]', '', regex=True).astype(float)

In [53]:
df.fillna(0)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",0,0,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",0,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",0,0,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",0,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",0,0,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",0,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",0,0,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",0,0,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,0,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",0,0,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,11890.0,INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",0,0,"[{""size"":""Onesize""}]","[""pi-13698258""]",0,0,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,8900.0,INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",0,0,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",0,0,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,7950.0,INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",0,0,"[{""size"":""Onesize""}]",0,0,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,2636.0,INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",0,Tru███m R███il,"[{""size"":""Onesize""}]",0,Sho███o. ███-10█████████enu███████████████████...,0,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,699.0,INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",0,0,"[{""size"":""Medium""}]",0,0,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [54]:
df[df['rating']>=4.0]

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,NaN,1399.0,INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",NaN,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,11791782,CASIO,Youth Digital Women Red Digital Watch I117 DW-...,4.6,29,3595,10.0,3235.0,INR,http://assets.myntassets.com/assets/images/117...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,Fla███ech███tai███,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...","3rd███165███th █████████, s███████████████████...",NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
993,19322504,V2A,Girls Blue Printed Dial & Pink Straps Digital ...,4.0,6,1599,50.0,799.0,INR,http://assets.myntassets.com/assets/images/193...,...,"{""1_star"":1,""2_stars"":0,""3_stars"":1,""4_stars"":...",NaN,Br ███erp███es,"[{""size"":""Onesize""}]",NaN,Kha███ no███122█████████lhi██████████████████,NaN,"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
994,8481603,French Connection,Women Silver-Toned Analogue Watch FCN0001B,4.5,149,6250,70.0,6250.0,INR,http://assets.myntassets.com/assets/images/848...,...,"{""1_star"":7,""2_stars"":1,""3_stars"":8,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8481603_cae700"",""https://videos.myntasset...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,8900.0,INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,2636.0,INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches

In [55]:
df[['product_id','title','category','rating','initial_price','discount']]

     product_id           title   category  rating  initial_price  discount
0       8376765     Lino Perros  backpacks     3.8           3995      58.0
1       9136281  Tommy Hilfiger  backpacks     4.5           2899      35.0
2      17633752           Lavie  backpacks     4.4           2999      65.0
3       1376949          F Gear  backpacks     4.4           1675      52.0
4      13939916       MYTRIDENT  bath-robe     4.7           2899      17.0
..          ...             ...        ...     ...            ...       ...
995    13698258           KREDO    watches     3.5          11890      50.0
996    16896006           GUESS    watches     5.0           8900      45.0
997     1708108        GIORDANO    watches     2.8           7950      50.0
998    19280114        Fastrack    watches     4.3           3295      20.0
999    18601682         BOLDFIT  yoga-mats     3.8            699      31.0

[1000 rows x 6 columns]

In [56]:
df.drop_duplicates()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,11890.0,INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,8900.0,INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,7950.0,INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,2636.0,INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,699.0,INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [57]:
print(df.shape)

(1000, 24)

In [58]:
df['total_amount']=df['final_price']*df['ratings_count']

In [59]:
df[['title','final_price','ratings_count','total_amount']]

              title  final_price  ratings_count  total_amount
0       Lino Perros       3995.0             15       59925.0
1    Tommy Hilfiger       2899.0             67      194233.0
2             Lavie       2999.0            226      677774.0
3            F Gear       1675.0           1052     1762100.0
4         MYTRIDENT       2899.0             12       34788.0
..              ...          ...            ...           ...
995           KREDO      11890.0             11      130790.0
996           GUESS       8900.0             22      195800.0
997        GIORDANO       7950.0              5       39750.0
998        Fastrack       2636.0             17       44812.0
999         BOLDFIT        699.0            161      112539.0

[1000 rows x 4 columns]

In [62]:
df['discount'] = df['discount'].fillna(0)

In [63]:
df['seller_name'] = df['seller_name'].fillna('Unknown')

In [64]:
df['seller_information'] = df['seller_information'].fillna('Unknown')

In [70]:
df.to_csv(r"C:\Users\Admin\Downloads\archive\Combined_dataset_CLEANED.csv",index=False)

In [71]:
print("FINALLY DID IT, THANK YOU!!!")

FINALLY DID IT, THANK YOU!!!

## Brief Summary

**Dataset:** Indian E-Commerce Products
**Original:** 1000 rows × 24 columns

### What I Did
- Loaded CSV into Pandas DataFrame
- Explored data — shape, columns, dtypes, head/tail
- Handled missing values — filled discount with 0, seller_name with Unknown
- Cleaned final_price — removed ₹ symbol, converted to float
- Filtered rows with rating >= 4.0 
- Removed duplicates — 0 found
- Created derived column: total_amount = final_price × ratings_count
- Saved cleaned file as Combined_dataset_CLEANED.csv

### Key Stats
 Value |
| Total Products = 1000 |
| Categories = 97 |
| Avg Final Price = ₹1,706 |
| Duplicates = 0 |